teacher_file: "teacher.icl"
student_files:
  - "test.icl"
test_questions:
  - question_one:
      function_name: addInt
      test_cases:
        - 2 3
        - 3 4
        - 2 3
  - question_two:
      function_name: subInt
      test_cases:
        - 3 4
        - 3 2
        - 23 32
