teacher_file: "teacher.icl"
student_files:
  - "test.icl"
test_questions:
  - q1:
      function_name: addInt
      test_cases:
        - [1,2,3]
        - [1,2,3]
        - [1,2,3]
  - q2:
      function_name: subInt
      test_cases:
        - 3 4
        - 3 2
        - 23 32
